name: FlutterLauncherBuilder
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - name: Collect APK
        uses: actions/upload-artifact@v3
        with: 
          name: release-files
          path: build/app/outputs/apk/release/*.apk
          
      
